export const IPC = {
  GROUP: {
    CREATE: 'group: create',
    FETCH_ALL: 'group: fetch all',
    FETCH_ALL_ACTIVE: 'group: fetch all active',
    FETCH: 'group: fetch',
    FETCH_LIST: 'group: fetch list',
    UPDATE: 'group: update',
    DELETE: 'group: delete',
    SELECT: 'group: select',
  },
  TAXE: {
    CREATE: 'taxe: create',
    FETCH_ALL: 'taxe: fetch all',
    FETCH: 'taxe: fetch',
    UPDATE: 'taxe: update',
  },
  ORIGIN: {
    FETCH_ALL: 'origin: fetch all',
  },
  PRODUCT: {
    FETCH_ALL: 'product: fetch all',
    CREATE: 'product: create',
    FETCH_ALL_ACTIVE: 'product: fetch all active',
    FETCH_ALL_BY_NAME: 'product: fetch all by name',
    FETCH_LIST: 'product: fetch list',
    FETCH: 'product: fetch',
    DELETE: 'product: delete',
    UPDATE: 'product: update',
  },
  PRODUCT_EAN: {
    CREATE: 'productean: create',
    DELETE: 'productean: delete',
    FETCH_ALL: 'productean: fetch all',
    FETCH_BY_PRD_ID: 'productean: fetch by prd id',
    FETCH_BY_EAN: 'productean: fetch by ean',
    GENERATE: 'productean: generate',
    UPDATE: 'productean: update',
  },
  STATES: {
    GET_STATES: 'states: get states',
    GET_CITIES: 'states: get cities',
  },
  STORES: {
    CREATE: 'stores: create',
    CHECK_EXISTS: 'stores: check exists',
    GET: 'stores: get',
    UPDATE: 'stores: update',
  },
  USER: {
    CREATE: 'user: create',
    LOGIN: 'user: login',
    DELETE: 'user: delete',
    FETCH: 'user: fetch',
    FETCH_LIST: 'user: fetch list',
    RECOVER: 'user: recover',
    UPDATE: 'user: update',
  },
}
